### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by iampav** [pjanouch/nokia-3310-fonts#1]
Hi, 

I was searching for a Nokia type font and found your work. 

I think it looks great. I wanted to ask in advance if you minded me downloading your font to use as the basis of a Nokia tribute watch in Android Wear, using the WatchMaker app?

Obviously I am not seeking to profit from this and the watches are usually shared on Google Plus under a group. I'd also give full credit to you for the font. 

I'd be happy to send am example of what I've done. I look forward to hearing from you. 

Regards, Paul

**Comment by pjanouch** [comment]
Hello,
this project is covered by the ISC license, which is included in several of the files. As long as you stay within its wide boundaries, do as you please. Since the fonts have been retraced, I don't think there's any more legal stuff to consider.

The resulting font files are more or less entirely generated and they don't matter to me.
