### ISSUE TITLE
Used tools question

### ISSUE THREAD

**Issue by Metaphore** [pjanouch/nokia-3310-fonts#2]
Hello Přemysl,
I just can't find another way to contact you, hope you don't mind if I ask my question here.

First of all great job!
A like a lot those Nokia pixel fonts and use few of them in my games. But now I would like to add some extra characters to it (Russian localization) and get lost in modern font edit software. Most of them made for TTF vector fonts and have no respect for bitmaps. I would be very thankful if you describe a bit how exactly you put your raster drawing from gimp into any of those font formats. Or perhaps you used any of font edit tools?

Thanks in advance!

**Comment by pjanouch** [comment]
Hi, wow, I can barely remember, it was a lot of manual work.

I think Pinta works better for such bitmaps. Anyway, one of the export formats of GIMP is https://en.wikipedia.org/wiki/X_PixMap so I split that somehow into individual letters and ran xform.c on it to get the main font source file, which I adjusted manually (thus it is really the primary data source here) and built nokia-generate-bdf.c with it in order to generate BDF files to be imported into fontforge.

If you want to edit the font, it'll probably be best if you just edit the generated BDF files with fontforge. It is a strange application but once you get past all the weird bits, it does everything you'll need, including creation of TrueType fonts.

Changes in the BDF files are relatively easy to parse back into sources (I just need to write the tool).

**Comment by Metaphore** [comment]
Hey thanks for explanation. Yep, FontForge almost killed me already. It's easy to edit sfd font files by adding new glyphs in pixel mode, but that leads to nowhere anyway because faked ttf has no outline and thus not valid for common usage. I can see ttf files in this repo open and read as valid (Win8), but they are empty on preview, has no outline too?

**Comment by pjanouch** [comment]
You're right, now they don't work for me either if I try opening them in GNOME Font Viewer (horrible misrender), and fontforge displays empty glyphs. It was just a bonus, anyway. You can use BDF directly on Linux and the source files are there so that you actually don't have to use TTF at all (i.e. you can write your own renderer). I had the intent to rewrite Snake II once but abandoned the idea.

You could try making a new TTF font if that helps anything. There haven't been any changes to fontforge in a long time, though, so I wouldn't bet on that https://fontforge.github.io/changelog.html
